### ISSUE TITLE
Raw view for HTML

### ISSUE THREAD

**Issue by binaryfire** [domdomegg/aws-ses-v2-local#14]
It'd be great to have an option to view the raw HTML for HTML emails. That would come in handy for debugging dynamic templates.

**Comment by domdomegg** [comment]
By the raw HTML, do you mean viewing the HTML source? If so, I think this should be fairly easily to implement.

**Comment by binaryfire** [comment]
Yep exactly! It's visible in the API but it'd be great to have a "View source" button in the UI too.
