### ISSUE TITLE
HTML E-Mails don't display in Firefox

### ISSUE THREAD

**Issue by DASPRiD** [domdomegg/aws-ses-v2-local#7]
First off, thanks a lot for this tool!

I've been using it in a new project for a while now, but I have the problem that HTML emails do not display at all in Firefox, so I always have to start Chrome for that.

There is no error message in the console, and the iframe is simply empty when inspecting it.

**Comment by domdomegg** [comment]
Thanks for the bug report @DASPRiD!

I've reviewed how this renders in Firefox and think it's a bug with Firefox itself, reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=695868

However, I've identified a workaround that should fix this. I've released this as aws-ses-v2-local version 2.1.1. I've tested it in Firefox 109.0.1, but it would helpful if you could let me know whether this fixes it for you too.
